import '@/app/globals.css';
import { cn } from '@/lib/utils';
import QueryProvider from '@/providers/react-query';
import { ThemeProvider } from '@/providers/theme';
import type { Metadata } from 'next';
import { Geist, Geist_Mono, Inter } from 'next/font/google';
import { NuqsAdapter } from 'nuqs/adapters/next';

const geistSans = Geist({
    variable: '--font-geist-sans',
    subsets: ['latin'],
});

const geistMono = Geist_Mono({
    variable: '--font-geist-mono',
    subsets: ['latin'],
});

const inter = Inter({
    variable: '--font-inter',
    subsets: ['latin'],
    weight: ['400', '500', '600', '700', '800'],
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }: LayoutProps<'/'>) {
    return (
        <html lang="en">
            <body className={cn(geistSans.variable, geistMono.variable, inter.variable, 'font-sans antialiased')}>
                <NuqsAdapter>
                    <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
                        <QueryProvider>{children}</QueryProvider>
                    </ThemeProvider>
                </NuqsAdapter>
            </body>
        </html>
    );
}
